### ISSUE TITLE
I cannot build because of 'module not found' error

### ISSUE THREAD

**Issue by nmin11** [aws-samples/amplify-nextjs-chat-app#7]
I've built all the backend stacks via the CDK, and finished setting up graphql and amplify, but the `npm run build` doesn't run, which is preventing me from trying this project.
Does anyone know of a solution?

<img width="1108" alt="스크린샷 2023-05-22 오전 8 06 30" src="https://github.com/aws-samples/amplify-nextjs-chat-app/assets/75058239/878b8515-0bd2-45d9-9e51-baf3fa3e9f02">

I've already gone through the process of deleting `package-lock.json` file and `node-modules` directory and reinstalling via `npm install`, but got the same error.

**Comment by NEEtojin** [comment]
Hi, nmin11. 
I had the same error. Try copying amplify-nextjs-chat-app/lib/graphql to amplify-nextjs-chat-app/src/  .
it worked for me.

**Comment by nmin11** [comment]
> Hi, nmin11. I hope I'm not too late. I had the same error. Try copying amplify-nextjs-chat-app/lib/graphql to amplify-nextjs-chat-app/src/ . it worked for me.

I've got it!
Actually, I think it was a different problem for me.
In previous, I selected TypeScript when run command `amplify add codegen`.
But this time I selected JavaScript and it ran successfully.

<img width="720" alt="스크린샷 2023-06-03 오후 4 48 31" src="https://github.com/aws-samples/amplify-nextjs-chat-app/assets/75058239/c5fde520-8560-4fdf-b052-5bc4ad3079c8">

The solution was different, but thanks for motivating me to try again!

**Comment by NEEtojin** [comment]
Happy to hear that :)
